app/armamento/models.py
from app import app, db

class Armamento(db.Model):
    __tablename__ = "armamento"
    
    id                  = db.Column(db.Integer, primary_key=True)
    nome_arma           = db.Column(db.String(100), nullable=False)
    tipo                = db.Column(db.String(20))
    valor               = db.Column(db.String(11))
    cartucho            = db.Column(db.String(15))
    penetrabilidade     = db.Column(db.String(15))
    cadência_de_tiro    = db.Column(db.String(30))
    

app/auxiliar/models.py
from app import app, db

class Auxiliar(db.Model):
    __tablename__ = "auxiliar"
    
    id                  = db.Column(db.Integer, primary_key=True)
    nome                = db.Column(db.String(100), nullable=False)
    descrição           = db.Column(db.String(50))
    

app/funcionario/models.py
from app import app, db

class Funcionario(db.Model):
    __tablename__ = "funcionario"
    
    id                  = db.Column(db.Integer, primary_key=True)
    nome                = db.Column(db.String(100), nullable=False)
    codinome            = db.Column(db.String(20))
    data_de_nascimento  = db.Column(db.String(11))
    cpf                 = db.Column(db.String(15))
    rg                  = db.Column(db.String(15))
    estado_civil        = db.Column(db.String(30))
    escolaridade        = db.Column(db.String(50))
    endereço            = db.Column(db.String(70))
    habilidades         = db.Column(db.String(60))
    celular             = db.Column(db.String(12))
    email               = db.Column(db.String(25))
    salario             = db.Column(db.String(20))
    
    missoes_presente    = db.Column(db.String(20))

app/missao/models.py
from app import app, db

class Missao(db.Model):
    __tablename__ = "missao"
    
    id                      = db.Column(db.Integer, primary_key=True)
    nome_missao             = db.Column(db.String(100), nullable=False)
    data                    = db.Column(db.String(20))
    local                   = db.Column(db.String(11))
    cliente                 = db.Column(db.String(15))
    status                  = db.Column(db.String(20))

    arsenal                 = db.Column(db.String(20))
    agentes_responsaveis    = db.Column(db.String(20))



 #(nome, data, local (com coordenadas) cliente, agente(s) responsável(eis) (deve-se poder criar sem agentes selecionados também), arsenal (deve-se poder criar sem arsenal selecionado também), status (completada, falhada, em aberto, em execução) e uma breve descrição)#

app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand


app = Flask(__name__)
app.config['SECRET_KEY'] = "senhafoda"

########################################
###############BANCO DE DADOS###########
########################################

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///"+os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)



########################################
###############BLUEPRINTS###############
########################################
from app.missao.views import missao
from app.funcionario.views import funcionario
from app.armamento.views import armamento
from app.principal.views import principal

app.register_blueprint(principal)
app.register_blueprint(funcionario, url_prefix="/funcionario")
app.register_blueprint(missao, url_prefix="/missao")
app.register_blueprint(armamento, url_prefix="/armamento")

app/armamento/views.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for
from app import db
from app.armamento.models import Armamento




armamento = Blueprint('armamento', __name__, template_folder='templates')

@armamento.route("/")
def index():
    return render_template('base_armamentos.html')

@armamento.route('/cadastrar_arma',  methods=['GET','POST'])
def cadastrar_arma():
    if request.method == 'POST':
        nome_arma = request.form['nome_arma']
        tipo = request.form['tipo']
        valor  = request.form['valor']
        cartucho  = request.form['cartucho']
        penetrabilidade  = request.form['penetrabilidade']
        cadência_de_tiro = request.form['cadência_de_tiro']


        armamento = Armamento(nome_arma = nome_arma,
                              tipo = tipo,
                              valor = valor,
                              cartucho = cartucho,
                              penetrabilidade = penetrabilidade,
                              cadência_de_tiro = cadência_de_tiro)
        db.session.add(armamento)
        db.session.commit()

        return redirect(url_for('armamento.index'))
    return render_template('form_armamentos.html')

app/funcionario/views.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for
from app import db
from app.funcionario.models import Funcionario




funcionario = Blueprint('funcionario', __name__, template_folder='templates')

@funcionario.route("/")
def index():
    funcionarios = Funcionario.query.all()
    return render_template('base_funcionarios.html', funcionarios_front  = funcionarios)

@funcionario.route('/cadastrar_funcionario', methods=['GET','POST'])
def cadastrar_funcionario():
    if request.method =='POST':
        nome = request.form['nome']
        codinome = request.form['codinome']
        data_de_nascimento = request.form['data_de_nascimento']
        cpf = request.form['cpf']
        rg = request.form['rg']
        estado_civil = request.form['estado_civil']
        escolaridade = request.form['escolaridade']
        endereço = request.form['endereço']
        habilidades = request.form['habilidades']
        celular = request.form['celular']
        email = request.form['email']
        salario = request.form['salario']

        
        
        funcionario = Funcionario(nome = nome,
                                  codinome = codinome,
                                  data_de_nascimento = 
                                  data_de_nascimento,
                                  cpf = cpf,
                                  rg = rg,
                                  estado_civil = estado_civil,
                                  escolaridade = escolaridade,
                                  endereço = endereço,
                                  habilidades = habilidades,
                                  celular = celular,
                                  email = email,
                                  salario = salario)
        db.session.add(funcionario)
        db.session.commit()

        return redirect(url_for('funcionario.index'))            
    return render_template('form_funcionarios.html')

@funcionario.route('/perfil/<_id>', methods=['GET'])
def perfil(_id):
    funcionario = Funcionario.query.get_or_404(_id)

    return render_template('info_funcionarios.html', funcionario = funcionario)




    

app/missao/views.py
from flask import Blueprint
from flask import render_template, request, redirect, url_for
from app import db
from app.missao.models import Missao


missao = Blueprint('missao', __name__, template_folder='templates')

@missao.route("/")
def index():
    return render_template('base_missoes.html')

@missao.route('/cadastrar_missao', methods=['GET','POST'])
def cadastrar_missao():
    if request.method == 'POST':
        nome_missao             = request.form['nome_missao']
        data                    = request.form['data']
        local                   = request.form['local']
        cliente                 = request.form['cliente']
        status                  = request.form['status']
        arsenal                 = request.form['arsenal']
        agentes_responsaveis    = request.form['']

        missao = Missao(nome_missao = nome_missao,
                        data = data,
                        local = local,
                        cliente = cliente,
                        status = status,
                        arsenal = arsenal,
                        agentes_responsaveis = agentes_responsaveis)
        db.session.add(missao)
        db.session.commit()
        
        return redirect(url_for('missao.index'))
    return render_template('form_missoes.html')

app/principal/views.py
from flask import Blueprint
from flask import render_template

principal = Blueprint('principal', __name__)

@principal.route("/")
def index():
    return render_template('base_inicial.html')

app/templates/base_armamentos.html
<!DOCTYPE html>
<html lang="pt_br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Armamento - VOOHP</title>

    <!-- Custom fonts for this template-->
    
    
    <!--Custom styles for this template-->

    <link href="{{url_for('static',filename='startbootstrap/css/sb-admin-2.min.css')}}" rel="stylesheet">
    

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav sidebar accordion" style="background-color: #0d122b;"id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{url_for('principal.index')}}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">VOOHP</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('principal.index')}}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Página inicial</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Opções
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('funcionario.index')}}" >
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Funcionários</span>
                </a>
                
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('missao.index')}}"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Missões</span>
                </a>
                
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('armamento.index')}}" 
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Armamento</span>
                </a>
                
            </li>

            <!-- Divider -->
            

            <!-- Heading -->
            

            <!-- Nav Item - Pages Collapse Menu -->
            

            <!-- Nav Item - Charts -->
           

            <!-- Nav Item - Tables -->
           

            <!-- Divider -->
            

            <!-- Sidebar Toggler (Sidebar) -->
            
            <!-- Sidebar Message -->
            

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
               
                <!-- Topbar -->
            
                <nav class="navbar navbar-expand topbar mb-4 static-top shadow"  style="background: #ffffff;">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <h2>Valorant organization of human protection</h2>
                    
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto ">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        
                        <!-- Nav Item - Alerts -->
                        

                        <!-- Nav Item - Messages -->
                        
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                       </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <img src="{{url_for('static', filename = 'sistema_jerry_img/V_Logomark_Red.png')}}" class="img-fluid" alt="BANNER">

                    
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-3 mt-5" style="color: #0d122b;">
                        <h1 class="h3 mb-0" style="font-weight: 600;" >Arsenal completo:</h1>
                    </div>

                    <!-- Content Row -->
                    <div class="row">
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">Arma</th>
                                <th scope="col">Informações</th>
                                
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <th scope="row">1</th>
                                <td>AK-47</td>
                                <td><button type="button" style="font-weight: 900; background: #d14841; color: #000;" class="btn btn-sm"> + </button></td>
                               
                              </tr>
                              <tr>
                                <th scope="row">2</th>
                                <td>MP5</td>
                                <td><button type="button" style="font-weight: 900; background: #d14841; color: #000;" class="btn btn-sm"> + </button></td>
                                
                              </tr>
                              <tr>
                                <th scope="row">3</th>
                                <td >Glock</td>
                                <td><button type="button" style="font-weight: 900; background: #d14841; color: #000;" class="btn btn-sm"> + </button></td>
                               </tr>
                            </tbody>
                        </table>

                        <a href="{{url_for('armamento.cadastrar_arma')}}" class="btn btn-lg btn-block mb-5" style="background: #d14841; color: #000000; font-weight: 500;">Adicionar nova arma</a>
                        
                    </div>                    
                    
                    <!-- Content Row -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-3 mt-5" style="color: #0d122b;">
                        <h1 class="h3 mb-0 mt-5" style="font-weight: 600;" >Armas auxiliares:</h1>
                    </div>
                    <div class="row">
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">#</th>
                                <th scope="col">Auxiliar</th>
                                <th scope="col">Informações</th>
                                
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <th scope="row">1</th>
                                <td>Bomba</td>
                                <td><button type="button" style="font-weight: 900; background: #d14841; color: #000;" class="btn btn-sm"> + </button></td>
                               
                              </tr>
                              <tr>
                                <th scope="row">2</th>
                                <td>Granada</td>
                                <td><button type="button" style="font-weight: 900; background: #d14841; color: #000;" class="btn btn-sm"> + </button></td>
                                
                              </tr>
                              <tr>
                                <th scope="row">3</th>
                                <td >C4</td>
                                <td><button type="button" style="font-weight: 900; background: #d14841; color: #000;" class="btn btn-sm"> + </button></td>
                               </tr>
                            </tbody>
                        </table>

                        <button type="button" class="btn btn-lg btn-block" style="background: #d14841; color: #000000; font-weight: 500;">Adicionar novo auxiliar</button>
                        
                        <!-- Content Column -->
                        <div class="col-lg-6 mb-4"></div>

                            

                            <!-- Color System -->
                            

                        <div class="col-lg-6 mb-4">

                            <!-- Illustrations -->
                            

                            <!-- Approach -->
                            

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer shadow" style="background: #ffffff; color: #0d122b;">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Origin &copy; 2020 - <i>tecnologie-se</i></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
   

    <!-- Logout Modal-->
   

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>

</body>

</html>

app/templates/base_funcionarios.html
<!DOCTYPE html>
<html lang="pt_br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Funcionários - VOOHP</title>

    <!-- Custom fonts for this template-->
    
    
    <!--Custom styles for this template-->

    <link href="{{url_for('static',filename='startbootstrap/css/sb-admin-2.min.css')}}" rel="stylesheet">
    


</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav sidebar accordion" style="background-color: #0d122b;"id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{url_for('principal.index')}}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">VOOHP</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('principal.index')}}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Página inicial</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Opções
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="{{url_for('funcionario.index')}}" >
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Funcionários</span>
                </a>
                
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item ">
                <a class="nav-link" href="{{url_for('missao.index')}}"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Missões</span>
                </a>
                
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{url_for('armamento.index')}}" 
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Armamento</span>
                </a>
                
            </li>

            <!-- Divider -->
            

            <!-- Heading -->
            

            <!-- Nav Item - Pages Collapse Menu -->
            

            <!-- Nav Item - Charts -->
           

            <!-- Nav Item - Tables -->
           

            <!-- Divider -->
            

            <!-- Sidebar Toggler (Sidebar) -->
            
            <!-- Sidebar Message -->
            

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
               
                <!-- Topbar -->
            
                <nav class="navbar navbar-expand topbar mb-4 static-top shadow"  style="background: #ffffff;">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <h2>Valorant organization of human protection</h2>
                    
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto ">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        
                        <!-- Nav Item - Alerts -->
                        

                        <!-- Nav Item - Messages -->
                        
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                       </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <img src="{{url_for('static', filename = 'sistema_jerry_img/V_Logomark_Grey.png')}}" class="img-fluid" alt="BANNER">

                    
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-3 mt-5" style="color: #0d122b;">
                        <h1 class="h3 mb-0" style="font-weight: 600;" >Lista de funcionários:</h1>
                    </div>

                    <!-- Content Row -->
                    <div class="row">
                        <table class="table">
                            <thead>
                              <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Funcionário</th>
                                <th scope="col">Opções</th>
                                
                              </tr>
                            </thead>
                            <tbody>
                            {% for funcionario in funcionarios_front %}
                              <tr>
                                <th scope="row">{{funcionario.id}}</th>
                                <td>{{funcionario.nome}}</td>
                                <td><div class="btn-group" role="group" aria-label="Basic example">
                                    <a href="{{url_for('funcionario.perfil',_id=funcionario.id)}}" style="background-color: #0d122b; color: #ffffff;"  class="btn">Ver mais</a>
                                    
                                    <a style="background-color: #0d122b; color: #ffffff;" class="btn">Excluir</a>

                                    <a style="background-color: #0d122b; color: #ffffff;" class="btn">Editar</a>
                                  </div></td>
                              </tr>
                              {% endfor %}
                              
                            </tbody>
                        </table>
                       

                        <a href="{{url_for('funcionario.cadastrar_funcionario')}}" class="btn btn-lg btn-block shadow" style="background: #d14841; color: #000000; font-weight: 600;">Adicionar novo funcionário</a>
                        
                    </div>                    
                    
                    <!-- Content Row -->
                    <div class="row">
                        
                        <!-- Content Column -->
                        <div class="col-lg-6 mb-4"></div>

                            

                            <!-- Color System -->
                            

                        <div class="col-lg-6 mb-4">

                            <!-- Illustrations -->
                            

                            <!-- Approach -->
                            

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer shadow" style="background: #ffffff; color: #0d122b;">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Origin &copy; 2020 - <i>tecnologie-se</i></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
   

    <!-- Logout Modal-->
   

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/chart-area-demo.js"></script>
    <script src="js/demo/chart-pie-demo.js"></script>

</body>

</html>